# Generated by Django 5.0.4 on 2024-04-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipment'),
        ('non_current_asset', '0002_alter_noncurrentasset_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер аудиторії')),
                ('description_aud', models.TextField(verbose_name='Опис')),
                ('head', models.CharField(max_length=255, verbose_name='ПІБ завідувача')),
            ],
            options={
                'verbose_name': 'Auditorium',
                'verbose_name_plural': 'Auditoriums',
                'db_table': 'auditorium',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInAuditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Дата останнього обслуговування')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='Дата ремонту')),
                ('note_equip', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorium.auditorium', verbose_name='Номер аудиторії')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='Обладнання')),
                ('non_current_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='non_current_asset.noncurrentasset', verbose_name='Необоротний актив')),
            ],
            options={
                'verbose_name': 'Equipment in Auditorium',
                'verbose_name_plural': 'Equipment in Auditoriums',
                'db_table': 'equipment_in_auditorium',
            },
        ),
    ]
