# Generated by Django 5.0.4 on 2024-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='description_aud',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='head',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ПІБ завідувача'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер аудиторії'),
        ),
    ]
