# Generated by Django 5.0.4 on 2024-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_alter_auditorium_description_aud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinauditorium',
            name='non_current_asset',
        ),
    ]
