# Generated by Django 5.0.4 on 2024-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_hdd_volume_alter_equipment_ram_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='screen_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва монітору'),
        ),
    ]
