# Generated by Django 5.0.4 on 2024-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='projector_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва проектору'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='router_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва комутатора'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='router_speed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Швидкість комутатора'),
        ),
    ]
