# Generated by Django 5.0.4 on 2024-04-21 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unreg_aud', models.CharField(max_length=255, verbose_name='Назва')),
                ('quantity_unreg_aud', models.IntegerField(verbose_name='Кількість')),
                ('description_unreg_aud', models.TextField(verbose_name='Опис')),
                ('date_of_entry', models.DateField(verbose_name='Дата внесення')),
                ('note_unreg_aud', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Не зареєстрований інвентар',
                'verbose_name_plural': 'Не зареєстровані інвентар',
                'db_table': 'unregistered_inventories',
            },
        ),
    ]
