# Generated by Django 5.0.4 on 2024-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unregistered_inventory', '0002_alter_unregisteredinventory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unregisteredinventory',
            name='user',
        ),
        migrations.AlterField(
            model_name='unregisteredinventory',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внесення'),
        ),
        migrations.AlterField(
            model_name='unregisteredinventory',
            name='description_unreg_aud',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='unregisteredinventory',
            name='name_unreg_aud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='unregisteredinventory',
            name='quantity_unreg_aud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість'),
        ),
    ]
