# Generated by Django 5.0.4 on 2024-04-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalappeals',
            options={'verbose_name_plural': 'Journal Appeals'},
        ),
        migrations.AlterModelTable(
            name='journalappeals',
            table='journal appeals',
        ),
    ]
