# Generated by Django 5.0.4 on 2024-05-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_appeals', '0002_alter_journalappeals_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journalappeals',
            table='Journal of appeals',
        ),
    ]
