# Generated by Django 5.0.4 on 2024-05-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_appeals', '0003_alter_journalappeals_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalappeals',
            options={'verbose_name_plural': 'Journal of appeals'},
        ),
    ]
