# Generated by Django 5.0.4 on 2024-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_appeals', '0005_remove_journalappeals_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalappeals',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус виконання'),
        ),
        migrations.AlterField(
            model_name='journalappeals',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='journalappeals',
            name='date_appeals',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подання заявки'),
        ),
        migrations.AlterField(
            model_name='journalappeals',
            name='description_problem',
            field=models.TextField(blank=True, null=True, verbose_name='Опис проблеми'),
        ),
        migrations.AlterField(
            model_name='journalappeals',
            name='problem_aud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ аудиторії'),
        ),
        migrations.AlterField(
            model_name='journalappeals',
            name='tel_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
