# Generated by Django 5.0.4 on 2024-05-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal_appeals', '0007_delete_journalappeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAppeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_aud', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ аудиторії')),
                ('description_problem', models.TextField(blank=True, null=True, verbose_name='Опис проблеми')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я")),
                ('tel_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('date_appeals', models.DateField(blank=True, null=True, verbose_name='Дата подання заявки')),
                ('Status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус виконання')),
            ],
            options={
                'verbose_name_plural': 'Journal of appeals',
                'db_table': 'Journal of appeals',
            },
        ),
    ]
