# Generated by Django 5.0.4 on 2024-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_current_asset', '0002_alter_noncurrentasset_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncurrentasset',
            name='arrival_mark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Відмітка про прибуття'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='balance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Балансова вартість'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='factory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводський номер'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='initial_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первісна вартість'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='journal_code',
            field=models.CharField(max_length=20, verbose_name='Код кафедри'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспортний номер'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='service_life',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Строк корисного використання'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='wear_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума зносу'),
        ),
    ]
