# Generated by Django 5.0.4 on 2024-04-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_current_asset', '0003_alter_noncurrentasset_arrival_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncurrentasset',
            name='acquisition_date',
            field=models.CharField(max_length=20, verbose_name='Дата придбання/введення в експлуатацію'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='decommissioning',
            field=models.CharField(blank=True, null=True, verbose_name='Дата списання'),
        ),
    ]
