# Generated by Django 5.0.4 on 2024-05-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_current_asset', '0005_alter_noncurrentasset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncurrentasset',
            name='object_number',
        ),
        migrations.AddField(
            model_name='noncurrentasset',
            name='bux_initial_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первісна вартість за бухгалтерськими даними'),
        ),
        migrations.AddField(
            model_name='noncurrentasset',
            name='bux_quantity_asset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість за бухгалтерськими даними'),
        ),
        migrations.AlterField(
            model_name='noncurrentasset',
            name='decommissioning',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата списання'),
        ),
    ]
