# Generated by Django 5.0.4 on 2024-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_remove_equipmentinauditorium_non_current_asset'),
        ('non_current_asset', '0006_remove_noncurrentasset_object_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonCurrentAsset',
        ),
    ]
