# Generated by Django 5.0.4 on 2024-05-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('non_current_asset', '0007_delete_noncurrentasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCurrentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_code', models.CharField(max_length=20, verbose_name='Код кафедри')),
                ('name_description', models.TextField(verbose_name='Найменування, стисла характеристика')),
                ('acquisition_date', models.CharField(max_length=20, verbose_name='Дата придбання/введення в експлуатацію')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Інвентарний номер')),
                ('factory_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводський номер')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспортний номер')),
                ('unit_of_measurement', models.CharField(max_length=20, verbose_name='Одиниця вимірювання')),
                ('quantity_asset', models.IntegerField(verbose_name='Кількість')),
                ('initial_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первісна вартість')),
                ('arrival_mark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Відмітка про прибуття')),
                ('bux_initial_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первісна вартість за бухгалтерськими даними')),
                ('bux_quantity_asset', models.IntegerField(blank=True, null=True, verbose_name='Кількість за бухгалтерськими даними')),
                ('wear_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума зносу')),
                ('balance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Балансова вартість')),
                ('service_life', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Строк корисного використання')),
                ('other_details', models.TextField(blank=True, null=True, verbose_name='Інші відомості')),
                ('placement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Розміщення')),
                ('decommissioning', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата списання')),
                ('person_in_charge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Відповідальний')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_current_assets', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Non Current Asset',
                'verbose_name_plural': 'Non Current Asset',
                'db_table': 'non_current_asset',
            },
        ),
    ]
