# Generated by Django 5.0.4 on 2024-05-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_current_asset', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncurrentasset',
            name='user',
        ),
    ]
